-- =============================================================================
-- 01 | Warehouse, database, and Role-Based Access Control (RBAC)
-- Run as ACCOUNTADMIN (or a role with CREATE privileges).
-- =============================================================================

-- Compute: small, auto-suspending warehouse to control cost.
CREATE WAREHOUSE IF NOT EXISTS FINSTREAM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS FINSTREAM;
CREATE SCHEMA IF NOT EXISTS FINSTREAM.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS FINSTREAM.RAW;

-- Functional roles mirroring the API's RBAC model (admin / analyst / viewer).
CREATE ROLE IF NOT EXISTS FINSTREAM_ADMIN;
CREATE ROLE IF NOT EXISTS FINSTREAM_ANALYST;
CREATE ROLE IF NOT EXISTS FINSTREAM_VIEWER;

-- Role hierarchy: admin inherits analyst inherits viewer (least privilege).
GRANT ROLE FINSTREAM_VIEWER  TO ROLE FINSTREAM_ANALYST;
GRANT ROLE FINSTREAM_ANALYST TO ROLE FINSTREAM_ADMIN;
GRANT ROLE FINSTREAM_ADMIN   TO ROLE SYSADMIN;

-- Warehouse usage.
GRANT USAGE ON WAREHOUSE FINSTREAM_WH TO ROLE FINSTREAM_VIEWER;

-- Read access for viewers; write/DDL for analysts and admins.
GRANT USAGE ON DATABASE FINSTREAM TO ROLE FINSTREAM_VIEWER;
GRANT USAGE ON SCHEMA FINSTREAM.ANALYTICS TO ROLE FINSTREAM_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA FINSTREAM.ANALYTICS TO ROLE FINSTREAM_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINSTREAM.ANALYTICS TO ROLE FINSTREAM_VIEWER;

GRANT USAGE ON SCHEMA FINSTREAM.RAW TO ROLE FINSTREAM_ANALYST;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FINSTREAM.RAW TO ROLE FINSTREAM_ANALYST;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA FINSTREAM.ANALYTICS TO ROLE FINSTREAM_ANALYST;
